// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removedeprecatedgoaldetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedeprecatedgoaldetail));
        
        string IMigrationMetadata.Id
        {
            get { return "201610271015462_remove-deprecated-goaldetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
